{% set name = "scrypt" %}
{% set version = "0.8.6" %}
{% set sha256 = "f8239b2d47fa1d40bc27efd231dc7083695d10c1c2ac51a99380360741e0362d" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256|lower }}

build:
  number: 1003
  script:
    - "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - openssl
    - cffi >=1.7
  run:
    - python
    - openssl
    - cffi >=1.7

test:
  imports:
    - scrypt
  commands:
    - conda inspect linkages -p $PREFIX scrypt  # [not win]
    - conda inspect objects -p $PREFIX scrypt   # [osx]

about:
  home: https://bitbucket.org/mhallin/py-scrypt/
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://bitbucket.org/mhallin/py-scrypt/
  doc_url: https://bitbucket.org/mhallin/py-scrypt/
  summary: 'This is a set of Python bindings for the scrypt key derivation function.'

extra:
  recipe-maintainers:
    - holgern
