travis:
  secure:
    BINSTAR_TOKEN: 0TkQr2XgC8zJi6oESO3cxhajjs05GByAmfSUZ8zjDHHMaU76fz1nh5UMxMbFK8Wwqzkc/2EwPBJB7R2G7BeeqpD6GKPlob3s61wQBPBfcmgA3cCbnyZUhHNsG0aXqs7K0P+MPjvISpcQLB7w4TekQoNNZhoWYu4ERoIMibL8+78RmdbCwm/N5jhtWBWl2bDL2KpfEuiSmsFvh8dKbHOFRBkZHAMMSZr39fCi9Kz+lyv12HUKqHquEgb740AgHjV7PiEIL2EwBZP6BhTw8QLNt0A0g6uWiYsP1Z/eWRNvRQWwMDeWImSiEFqi9cjWCWOgUPBzQP5PY31uC271fx1R6Gfyhzr4dNKnZgv9T+8Bx0J6UAdgddthiTajbgmgCHdClFhbEhug6HFg+LsrHehoCiTBsLo8RXu4iLOEXHAzf9KGNXdSWIvBK4A6Op2Evv0OKdtMiDvNdnG4q8F5VS75l1tMa3htCUgZVezIKvM9e8fUESwSAP3drZ50OOjmRWoU1Hn8wrRu4h7Ua9v/opkJkyWIRcaAG4G2aWpGMc50pNyt85LgSZzLd5iJgyOKfD/8EcAXBCHLd3KOW8J7HSuffkaLMNEYwzOV/DSjeqABLc7QZ3djUII8dKG3zNo3kGBOXSx89ud80+Gv3yNe/Z1xyB9jSesyp+0pipXWEG+vAvA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
